# Generated by Django 5.0.4 on 2025-09-01 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveType', models.CharField(max_length=50)),
                ('applyDate', models.DateTimeField(auto_now_add=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('reason', models.TextField()),
                ('deptApproval', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=10)),
                ('HRApproval', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=10)),
                ('finalApproval', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=10)),
                ('remarks', models.CharField(default='', max_length=100)),
                ('HRApprovedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HR_approved_leave', to='employee.employee')),
                ('deptApprovedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dept_approved_leave', to='employee.employee')),
                ('dutyHandOver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaveApplicationsHandOver', to='employee.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaveApplicationsEmployee', to='employee.employee')),
                ('finalApprovedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_approved_leave', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='VisitApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applyDate', models.DateTimeField(auto_now_add=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('visitTo', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('deptApproval', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=10)),
                ('HRApproval', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=10)),
                ('finalApproval', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=10)),
                ('remarks', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='attendance_photos/')),
                ('latitude', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('HRApprovedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HR_approved_visit', to='employee.employee')),
                ('deptApprovedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dept_approved_visit', to='employee.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitApplicationsEmployee', to='employee.employee')),
                ('finalApprovedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_approved_visit', to='employee.employee')),
            ],
        ),
    ]
