# Generated by Django 5.0.4 on 2025-08-07 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_reimbursements_moneyrecieved'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplications',
            name='dutyHandOver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leaveApplicationsHandOver', to='employee.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapplications',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaveApplicationsEmployee', to='employee.employee'),
        ),
    ]
