# Generated by Django 5.0.4 on 2025-08-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leaveapplications_dutyhandover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplications',
            old_name='status',
            new_name='HRApproval',
        ),
        migrations.AddField(
            model_name='leaveapplications',
            name='deptApproval',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='leaveapplications',
            name='finalApproval',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
