# Generated by Django 5.0.4 on 2025-08-07 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_reimbursements_moneyrecieved'),
        ('leave', '0003_rename_status_leaveapplications_hrapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplications',
            name='HRApprovedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HR_approved_leave', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='leaveapplications',
            name='deptApprovedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dept_approved_leave', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='leaveapplications',
            name='finalApprovedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_approved_leave', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='leaveapplications',
            name='HRApproval',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaveapplications',
            name='deptApproval',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaveapplications',
            name='finalApproval',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
