# Generated by Django 5.0.4 on 2025-08-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaveapplications_hrapprovedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplications',
            name='HRApproval',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaveapplications',
            name='deptApproval',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaveapplications',
            name='finalApproval',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=10),
        ),
    ]
