# Generated by Django 5.0.4 on 2025-08-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_alter_leaveapplications_hrapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplications',
            name='remarks',
            field=models.CharField(default='', max_length=100),
        ),
    ]
