# Generated by Django 5.0.4 on 2025-08-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leaveapplications_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplications',
            name='applyDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
