# Generated by Django 5.0.4 on 2025-08-13 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_alter_employee_annualleave_and_more'),
        ('leave', '0007_alter_leaveapplications_applydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applyDate', models.DateTimeField(auto_now_add=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('visitTo', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('deptApproval', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=10)),
                ('HRApproval', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=10)),
                ('finalApproval', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=10)),
                ('remarks', models.CharField(default='', max_length=100)),
                ('HRApprovedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HR_approved_visit', to='employee.employee')),
                ('deptApprovedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dept_approved_visit', to='employee.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitApplicationsEmployee', to='employee.employee')),
                ('finalApprovedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_approved_visit', to='employee.employee')),
            ],
        ),
    ]
