# Generated by Django 5.0.4 on 2025-08-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_visitapplications'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitapplications',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/'),
        ),
    ]
