# Generated by Django 5.0.4 on 2025-08-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_visitapplications_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitapplications',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitapplications',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
