# Generated by Django 5.0.4 on 2025-09-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casualLeave', models.IntegerField()),
                ('medicallLeave', models.IntegerField()),
                ('annualLeave', models.IntegerField()),
                ('otherLeave', models.IntegerField()),
                ('leaveNotification', models.BooleanField(default=False)),
                ('visitNotification', models.BooleanField(default=False)),
                ('officeStartTime', models.TimeField()),
                ('weekend', models.CharField(default='Friday', max_length=100)),
            ],
        ),
    ]
