# Generated by Django 5.0.4 on 2025-08-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casualLeave', models.IntegerField()),
                ('medicallLeave', models.IntegerField()),
                ('annualLeave', models.IntegerField()),
                ('otherLeave', models.IntegerField()),
            ],
        ),
    ]
