# Generated by Django 5.0.4 on 2025-08-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='leaveNotification',
            field=models.BooleanField(default=False),
        ),
    ]
