# Generated by Django 5.0.4 on 2025-08-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_globalconfig_leavenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='visitNotification',
            field=models.BooleanField(default=False),
        ),
    ]
