# Generated by Django 5.0.4 on 2025-08-18 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_globalconfig_visitnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='officeStartTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
