# Generated by Django 5.0.4 on 2025-08-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_globalconfig_officestarttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='weekend',
            field=models.CharField(default='Friday', max_length=100),
        ),
    ]
