# Generated by Django 5.0.4 on 2025-09-01 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('inclusionDate', models.CharField(max_length=100)),
                ('fuelReimbursement', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerPrintID', models.IntegerField(unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('join_date', models.DateField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('status', models.CharField(max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('casualLeave', models.IntegerField(default=10)),
                ('medicalLeave', models.IntegerField(default=10)),
                ('annualLeave', models.IntegerField(default=15)),
                ('otherLeave', models.IntegerField(default=10)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee.designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_covered', models.FloatField()),
                ('purpose', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_usages', to='employee.car')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_usages', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_awarded', models.DateField()),
                ('amount', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reimbursement', models.CharField(max_length=15)),
                ('allocationDate', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='accomodation_reimbursement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomodations', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_insurances', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LunchEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileModel', models.CharField(max_length=15)),
                ('allocationDate', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('file', models.FileField(upload_to='mobile_reimbursement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Reimbursements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField()),
                ('dateRequested', models.DateField(auto_now_add=True)),
                ('deptApproval', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('commercialApproval', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('finalApproval', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('moneyRecieved', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=100)),
                ('purchasedFrom', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='reimbursement_files')),
                ('commercialApprovedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_approved_reimbursements', to='employee.employee')),
                ('deptApprovedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dept_approved_reimbursements', to='employee.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='employee.employee')),
                ('finalApprovedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_approved_reimbursements', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TravelAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=15)),
                ('allocationDate', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelAllowance', to='employee.employee')),
            ],
        ),
    ]
