# Generated by Django 5.2.4 on 2025-07-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='department',
        ),
    ]
