# Generated by Django 5.2.4 on 2025-08-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_healthinsurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('inclusionDate', models.CharField(max_length=100)),
                ('fuelReimbursement', models.CharField(max_length=100)),
            ],
        ),
    ]
