# Generated by Django 5.2.4 on 2025-08-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuelReimbursement',
            field=models.FloatField(),
        ),
    ]
