# Generated by Django 5.2.4 on 2025-08-02 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_car_fuelreimbursement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileModel', models.CharField(max_length=15)),
                ('allocationDate', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='employee.employee')),
            ],
        ),
    ]
