# Generated by Django 5.2.4 on 2025-08-02 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='file',
            field=models.FileField(default='', upload_to='mobile_reimbursement'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reimbursement', models.CharField(max_length=15)),
                ('allocationDate', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='accomodation_reimbursement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomodations', to='employee.employee')),
            ],
        ),
    ]
