# Generated by Django 5.2.4 on 2025-08-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_mobile_file_accomodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=15)),
                ('allocationDate', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelAllowance', to='employee.employee')),
            ],
        ),
    ]
