# Generated by Django 5.2.4 on 2025-08-03 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_travelallowance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('distance_covered', models.FloatField()),
                ('purpose', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_usages', to='employee.car')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_usages', to='employee.employee')),
            ],
        ),
    ]
