# Generated by Django 5.2.4 on 2025-08-03 06:05

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_carusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carusage',
            name='destination',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carusage',
            name='endTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carusage',
            name='origin',
            field=models.CharField(default=datetime.datetime(2025, 8, 3, 6, 4, 58, 658027, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carusage',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2025, 8, 3, 6, 5, 38, 932639, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
