# Generated by Django 5.0.4 on 2025-08-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_lunchenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
