# Generated by Django 5.0.4 on 2025-08-04 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_designation_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField()),
                ('dateRequested', models.DateField(auto_now_add=True)),
                ('deptApproval', models.BooleanField(default=False)),
                ('commercialApproval', models.BooleanField(default=False)),
                ('finalApproval', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=100)),
                ('purchasedFrom', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='reimbursement_files')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='employee.employee')),
            ],
        ),
    ]
