# Generated by Django 5.0.4 on 2025-08-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_reimbursements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursements',
            name='commercialApproval',
            field=models.CharField(default='False', max_length=100),
        ),
        migrations.AlterField(
            model_name='reimbursements',
            name='deptApproval',
            field=models.CharField(default='False', max_length=100),
        ),
        migrations.AlterField(
            model_name='reimbursements',
            name='finalApproval',
            field=models.CharField(default='False', max_length=100),
        ),
    ]
