# Generated by Django 5.0.4 on 2025-08-04 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_reimbursements_commercialapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursements',
            name='commercialApprovedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_approved_reimbursements', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='reimbursements',
            name='deptApprovedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dept_approved_reimbursements', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='reimbursements',
            name='finalApprovedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_approved_reimbursements', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='reimbursements',
            name='commercialApproval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reimbursements',
            name='deptApproval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reimbursements',
            name='finalApproval',
            field=models.BooleanField(default=False),
        ),
    ]
