# Generated by Django 5.0.4 on 2025-08-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_reimbursements_commercialapprovedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursements',
            name='commercialApproval',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='reimbursements',
            name='deptApproval',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='reimbursements',
            name='finalApproval',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
