# Generated by Django 5.0.4 on 2025-08-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_alter_reimbursements_commercialapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursements',
            name='moneyRecieved',
            field=models.BooleanField(default=False),
        ),
    ]
