# Generated by Django 5.0.4 on 2025-08-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_reimbursements_moneyrecieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annualLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='casualLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='medicalLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='otherLeave',
            field=models.IntegerField(default=0),
        ),
    ]
