# Generated by Django 5.0.4 on 2025-08-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_employee_annualleave_employee_casualleave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='annualLeave',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='casualLeave',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='medicalLeave',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='otherLeave',
            field=models.IntegerField(default=10),
        ),
    ]
