# Generated by Django 5.0.4 on 2025-08-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_alter_employee_annualleave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fingerPrintID',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
