# Generated by Django 5.0.4 on 2025-08-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_employee_fingerprintid'),
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projectLeader',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee'),
        ),
    ]
