# Generated by Django 5.0.4 on 2025-08-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_projects_projectleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
