# Generated by Django 5.0.4 on 2025-08-30 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_employee_fingerprintid'),
        ('wms', '0003_task_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assignTime', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('progress', models.FloatField(default=0)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='edited_tasks', to='employee.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='wms.task')),
            ],
        ),
    ]
