# Generated by Django 5.0.4 on 2025-09-01 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_email', models.CharField(max_length=100)),
                ('agent_contact', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='crm.customer')),
            ],
            options={
                'unique_together': {('customer', 'agent_email')},
            },
        ),
        migrations.CreateModel(
            name='CustomerVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('potentialScope', models.CharField(blank=True, max_length=100, null=True)),
                ('scopeFile', models.FileField(upload_to='files')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customeragent')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('visit_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.visitapplications')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('scopeOfSupply', models.CharField(blank=True, max_length=100, null=True)),
                ('scopeFile', models.FileField(blank=True, null=True, upload_to='files')),
                ('note', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('offerSubmissionDate', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customeragent')),
                ('assignedTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadAssignedTo', to='employee.employee')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('customerVisit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customervisits')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadGeneratedBy', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('negoDate', models.DateField(blank=True, null=True)),
                ('tgtPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offerValue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('offerFile', models.FileField(blank=True, null=True, upload_to='files')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='OfferFilesPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.JSONField()),
                ('proposals', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('limitingDate', models.DateField(default=django.utils.timezone.now)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerFileGeneration', to='crm.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('advance_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('poRef', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='crm.offer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='orderfiles')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderFile', to='crm.order')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleOrderReference', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('invoiceDate', models.DateField(blank=True, null=True)),
                ('invoiceRef', models.CharField(blank=True, max_length=100, null=True)),
                ('totalInvoiceValue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ait', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='crm.order')),
            ],
        ),
        migrations.CreateModel(
            name='AccountsRecieveable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceRef', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentDate', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('totalInvoiceValue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountsRecieveable', to='crm.sales')),
            ],
        ),
    ]
