# Generated by Django 5.0.4 on 2025-08-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0023_employee_fingerprintid'),
        ('leave', '0010_visitapplications_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_email', models.CharField(max_length=100)),
                ('agent_contact', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
            options={
                'unique_together': {('customer', 'agent_email')},
            },
        ),
        migrations.CreateModel(
            name='CustomerVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('note', models.CharField(max_length=100)),
                ('potentialScope', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customeragent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('visit_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.visitapplications')),
            ],
            options={
                'unique_together': {('customer', 'visit_date', 'visit_time')},
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('scopeOfSupply', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('customerVisit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customervisits')),
            ],
            options={
                'unique_together': {('customerVisit', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_date', models.DateField(auto_now_add=True)),
                ('offer_details', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lead')),
            ],
            options={
                'unique_together': {('lead', 'offer_date')},
            },
        ),
    ]
