# Generated by Django 5.0.4 on 2025-08-23 15:48

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customervisits',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customervisits',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customervisits',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 23, 15, 48, 35, 83880)),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='customervisits',
            name='visit_date',
        ),
        migrations.RemoveField(
            model_name='customervisits',
            name='visit_time',
        ),
    ]
