# Generated by Django 5.0.4 on 2025-09-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerfilespdf',
            name='customerEmployeePosition',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='offerfilespdf',
            name='termsAndConditions',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='offerfilespdf',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
