# Generated by Django 5.0.4 on 2025-08-23 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_customervisits_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeragent',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='crm.customer'),
        ),
    ]
