# Generated by Django 5.0.4 on 2025-09-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_offerfilespdf_customeremployeeposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerfilespdf',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
