# Generated by Django 5.0.4 on 2025-08-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_customeragent_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervisits',
            name='scopeFile',
            field=models.FileField(default='', upload_to='files'),
            preserve_default=False,
        ),
    ]
