# Generated by Django 5.0.4 on 2025-08-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customervisits_scopefile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='customerVisit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customervisits'),
        ),
    ]
