# Generated by Django 5.0.4 on 2025-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_lead_unique_together_lead_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='scopeFile',
            field=models.FileField(default='', upload_to='files'),
            preserve_default=False,
        ),
    ]
