# Generated by Django 5.0.4 on 2025-08-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_lead_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='note',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
