# Generated by Django 5.0.4 on 2025-08-24 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_lead_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='offerSubmissionDate',
            field=models.DateField(default=datetime.datetime(2025, 8, 24, 11, 49, 46, 425194)),
            preserve_default=False,
        ),
    ]
