# Generated by Django 5.0.4 on 2025-08-24 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_lead_offersubmissiondate'),
        ('employee', '0023_employee_fingerprintid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
