# Generated by Django 5.0.4 on 2025-08-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_lead_employee'),
        ('employee', '0023_employee_fingerprintid'),
        ('leave', '0010_visitapplications_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customervisits',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customeragent'),
        ),
        migrations.AlterField(
            model_name='customervisits',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='customervisits',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='customervisits',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customervisits',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customervisits',
            name='potentialScope',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customervisits',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customervisits',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customervisits',
            name='visit_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.visitapplications'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='offerSubmissionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='scopeFile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='scopeOfSupply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
