# Generated by Django 5.0.4 on 2025-08-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_customervisits_agent_and_more'),
        ('employee', '0023_employee_fingerprintid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assignedTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadAssignedTo', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadGeneratedBy', to='employee.employee'),
        ),
    ]
