# Generated by Django 5.0.4 on 2025-08-24 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_lead_assignedto_alter_lead_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='crm.lead'),
        ),
    ]
