# Generated by Django 5.0.4 on 2025-08-24 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_offer_lead'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='negoDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='offer',
            name='tgtPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_details',
        ),
    ]
