# Generated by Django 5.0.4 on 2025-08-24 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_offer_unique_together_offer_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='negoDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
