# Generated by Django 5.0.4 on 2025-08-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_offer_discount_alter_offer_negodate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
