# Generated by Django 5.0.4 on 2025-08-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_offer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offerFile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
