# Generated by Django 5.0.4 on 2025-08-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_order_orderfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offerValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='poRef',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
