# Generated by Django 5.0.4 on 2025-08-25 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_offer_offervalue_order_poref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceDate', models.DateField(blank=True, null=True)),
                ('invoiceRef', models.CharField(blank=True, max_length=100, null=True)),
                ('totalInvoiceValue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='crm.order')),
            ],
        ),
    ]
