# Generated by Django 5.0.4 on 2025-08-25 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='ait',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='AccountsRecieveable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('paymentDate', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountsRecieveable', to='crm.sales')),
            ],
        ),
    ]
