# Generated by Django 5.0.4 on 2025-08-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_sales_ait_sales_vat_accountsrecieveable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsrecieveable',
            name='dueDate',
        ),
    ]
