# Generated by Django 5.0.4 on 2025-08-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_remove_accountsrecieveable_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='saleOrderReference',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
