# Generated by Django 5.0.4 on 2025-08-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_sales_saleorderreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsrecieveable',
            name='invoiceRef',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
