# Generated by Django 5.0.4 on 2025-08-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_accountsrecieveable_invoiceref'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsrecieveable',
            name='totalInvoiceValue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
