# Generated by Django 5.0.4 on 2025-08-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_accountsrecieveable_totalinvoicevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsrecieveable',
            name='totalInvoiceValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
