# Generated by Django 5.0.4 on 2025-08-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='inTime',
            field=models.TimeField(),
        ),
    ]
