# Generated by Django 5.0.4 on 2025-08-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_intime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='inTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
