# Generated by Django 5.0.4 on 2025-08-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_intime'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/'),
        ),
    ]
