# Generated by Django 5.0.4 on 2025-08-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_photo'),
        ('employee', '0023_employee_fingerprintid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
