# Generated by Django 5.0.4 on 2025-08-20 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_employeelocation'),
        ('employee', '0023_employee_fingerprintid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelocation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeLocations', to='employee.employee'),
        ),
    ]
